---
deployment:
  tasks:
    - export DEPLOYPATH=/home/catbxjbt/public_html/red/
    - /bin/cp src/header.html $DEPLOYPATH    
    - /bin/cp src/ennakointi.html $DEPLOYPATH
    - /bin/cp src/footer.html $DEPLOYPATH    
    - /bin/cp src/webflow.css $DEPLOYPATH
    - /bin/cp src/webflow.js $DEPLOYPATH    
    - /bin/cp src/haehakusanalla.php $DEPLOYPATH
    - /bin/cp src/index.html $DEPLOYPATH
    - /bin/cp src/sqltest.php $DEPLOYPATH
    - /bin/cp src/vaesto.html $DEPLOYPATH
    - /bin/cp src/tyollisyys.html $DEPLOYPATH
    - /bin/cp src/opiskelu.html $DEPLOYPATH
    - /bin/cp src/aluekehitys.html $DEPLOYPATH
    - /bin/cp src/toimialaennakointi.html $DEPLOYPATH
    - /bin/cp src/tyomarkkinasignaalit.html $DEPLOYPATH
    - /bin/cp src/webflow-contact.html $DEPLOYPATH
    - /bin/cp src/otsikot.html $DEPLOYPATH