---
deployment:
  tasks:
    - export DEPLOYPATH=/home/catbxjbt/public_html/
    - export DEPLOYPATHSWIPER=/home/catbxjbt/public_html/swiper/
    - export DEPLOYPATHAI=/home/catbxjbt/public_html/Ai/
    - /bin/cp src/header.html $DEPLOYPATH    
    - /bin/cp src/ennakointi.html $DEPLOYPATH
    - /bin/cp src/footer.html $DEPLOYPATH    
    - /bin/cp src/webflow.css $DEPLOYPATH
    - /bin/cp src/webflow.js $DEPLOYPATH    
    - /bin/cp src/haehakusanalla.php $DEPLOYPATH
    - /bin/cp src/index.html $DEPLOYPATH
    - /bin/cp src/haeMaakunnalla.php $DEPLOYPATH
    - /bin/cp src/vaesto.html $DEPLOYPATH
    - /bin/cp src/vaesto_historia.php $DEPLOYPATH
    - /bin/cp src/tyollisyys.html $DEPLOYPATH
    - /bin/cp src/tyollisyys.php $DEPLOYPATH    
    - /bin/cp src/tyollisyys_historia.php $DEPLOYPATH
    - /bin/cp src/tyonhakijat_historia.php $DEPLOYPATH
    - /bin/cp src/avoimetpainat_historia.php $DEPLOYPATH
    - /bin/cp src/opiskelu.html $DEPLOYPATH
    - /bin/cp src/vieraskieliset_historia.php $DEPLOYPATH
    - /bin/cp src/opiskelu.php $DEPLOYPATH    
    - /bin/cp src/opiskelu_historia.php $DEPLOYPATH
    - /bin/cp src/aluekehitys.html $DEPLOYPATH
    - /bin/cp src/tki_historia.php $DEPLOYPATH
    - /bin/cp src/talous_historia.php $DEPLOYPATH
    - /bin/cp src/alueentyopaikat_historia.php $DEPLOYPATH
    - /bin/cp src/db.php $DEPLOYPATH
    - /bin/cp src/mediaseuranta.html $DEPLOYPATH
    - /bin/cp src/toimialaennakointi.html $DEPLOYPATH
    - /bin/cp src/tyomarkkinasignaalit.html $DEPLOYPATH
    - /bin/cp src/webflow-contact.html $DEPLOYPATH
    - /bin/cp src/otsikot.html $DEPLOYPATH
    - /bin/cp src/info.html $DEPLOYPATH
    - /bin/cp src/analyysit.html $DEPLOYPATH
    - /bin/cp src/saavutettavuusseloste.html $DEPLOYPATH
    - /bin/cp src/swiper/effect-carousel.min.css $DEPLOYPATHSWIPER
    - /bin/cp src/swiper/effect-carousel.min.js $DEPLOYPATHSWIPER
    - /bin/cp src/swiper/swiper.html $DEPLOYPATHSWIPER
    - /bin/cp src/swiper/megatrendit.html $DEPLOYPATHSWIPER
    - /bin/cp src/Ai/ai_dashboard.html $DEPLOYPATHAI
    - /bin/cp src/Ai/database_news_collector.php $DEPLOYPATHAI
    - /bin/cp src/Ai/news_working_test.php $DEPLOYPATHAI
    - /bin/cp src/Ai/ai_analyzer_api.php $DEPLOYPATHAI
    - /bin/cp src/Ai/ai_analyzer_demo.html $DEPLOYPATHAI
    - /bin/cp src/Ai/ai_news_analyzer.py $DEPLOYPATHAI
    - /bin/cp src/Ai/advanced_news_intelligence.py $DEPLOYPATHAI
    - /bin/cp src/Ai/news_intelligence_api.php $DEPLOYPATHAI
    - /bin/cp src/Ai/news_test_curl.php $DEPLOYPATHAI
    - /bin/cp src/Ai/simple_news_test.php $DEPLOYPATHAI
    - /bin/cp src/Ai/news_collector.php $DEPLOYPATHAI
    - /bin/cp src/Ai/config.php $DEPLOYPATHAI
    - /bin/cp src/Ai/ai_config.py $DEPLOYPATHAI
    - /bin/cp src/Ai/README.md $DEPLOYPATHAI
    # NOTE: ai_config.json must be uploaded manually for security (not in version control)
