INSERT INTO catbxjbt_ennakointi.Mediaseuranta (Maakunta_ID,Teema,uutisen_pvm,Uutinen,Url,Hankkeen_luokitus,ai_analysis_status,ai_analyzed_at,ai_relevance_score,ai_economic_impact,ai_employment_impact,ai_key_sectors,ai_sentiment,ai_crisis_probability,ai_summary,ai_keywords,ai_full_analysis,ai_processing_time,competitive_analysis_status,competitive_analyzed_at,competitive_analysis,competitors_mentioned,funding_intelligence,market_opportunities,partnership_opportunities,competitive_score,business_relevance,strategic_importance,competitive_threats,market_intelligence,action_recommendations) VALUES
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-26',N'Lahden yritysmyönteisyys parantunut edelleen - Ladecin suositteluhalukkuus suurten kaupunkien korkein',N'https://www.ladec.fi/tiedotteet/lahden-yritysmyonteisyys-parantunut-edelleen-ladecin-suositteluhalukkuus-suurten-kaupunkien-korkein',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Koulutus ja tutkimus','2025-11-14',N'LUT-?yliopiston tavoitteet jälleen korkealla: järjestää Lahdessa "yliopistohistorian suurimman kasvutapahtuman"',N'https://www.ess.fi/paikalliset/8998656?utm_source=Lahti+vahvassa+nousussa%C2%A0%7C+V%C3%A4%C3%A4ksyyn+maailman+suurin+hiekka-akku%C2%A0%7C%C2%A0Luhta+pukee+Suomen+Olympiajoukkueen&utm_medium=email&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-18',N'Lah­ti kun­tien elin­voi­ma­ver­tai­lun vah­va nou­si­ja',N'https://www.lahti.fi/uutiset/lahti-kuntien-elinvoimavertailun-vahva-nousija/',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-06',N'Keskuskauppakamari: Joka toisessa työnantajayrityksessä on ulkomaalaistaustaista henkilöstöä – kynnystä kansainvälisen osaajan palkkaamiseen tulee madaltaa',N'https://kauppakamari.fi/tiedote/keskuskauppakamari-joka-toisessa-tyonantajayrityksessa-on-ulkomaalaistaustaista-henkilostoa-kynnysta-kansainvalisen-osaajan-palkkaamiseen-tulee-madaltaa/',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-24',N'Lah­teen tar­vi­taan uu­si ho­tel­li – mark­ki­na­tut­ki­mus pal­jas­taa mer­kit­tä­vän in­ves­toin­ti­mah­dol­li­suu­den',N'https://www.lahti.fi/uutiset/lahteen-tarvitaan-uusi-hotelli-markkinatutkimus-paljastaa-merkittavan-investointimahdollisuuden/',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-26',N'Nastolan sote-pela-keskusta sovitellaan enää vain Rakokiveen – aluehallitus esittää rakentamisrahaa ensi vuodelle',N'https://yle.fi/a/74-20196153',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-25',N'Lahti-Energia: Vääksyyn rakennetaan maailman suurin hiekka-akku',N'https://yle.fi/a/74-20195997',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Muutosneuvottelut, irtisanomiset, konkurssit, investointien perumiset ja tulosten heikentymiset','2025-11-24',N'Lahden yt-neuvottelut päättyivät – tarkka tulos ei vielä tiedossa, mutta henkilöstön vähennystarve pieneni',N'https://yle.fi/a/74-20195807',N'Työllisyys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL);
INSERT INTO catbxjbt_ennakointi.Mediaseuranta (Maakunta_ID,Teema,uutisen_pvm,Uutinen,Url,Hankkeen_luokitus,ai_analysis_status,ai_analyzed_at,ai_relevance_score,ai_economic_impact,ai_employment_impact,ai_key_sectors,ai_sentiment,ai_crisis_probability,ai_summary,ai_keywords,ai_full_analysis,ai_processing_time,competitive_analysis_status,competitive_analyzed_at,competitive_analysis,competitors_mentioned,funding_intelligence,market_opportunities,partnership_opportunities,competitive_score,business_relevance,strategic_importance,competitive_threats,market_intelligence,action_recommendations) VALUES
	 (1,N'Muutosneuvottelut, irtisanomiset, konkurssit, investointien perumiset ja tulosten heikentymiset','2025-11-19',N'Teboil-yrittäjä ajautuu toiseen konkurssiin – pakotteet sulkevat Heinolan aseman',N'https://yle.fi/a/74-20194898',N'Työllisyys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Aluekehitys, kulkuyhteydet ja kaavoitus','2025-11-18',N'Vääksyn hotelli Tallukka kiinalais­­omistukseen – omistaja toivoo saavansa lisää kiinalais­­matkailijoita Päijät-Hämeeseen',N'https://yle.fi/a/74-20194706',N'Tapahtumat ja matkailu',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Muutosneuvottelut, irtisanomiset, konkurssit, investointien perumiset ja tulosten heikentymiset','2025-11-14',N'Heinolan Tähtihovi sulkee ovensa ',N'https://yle.fi/a/74-20194201',N'Työllisyys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-13',N'S-ryhmän ja Keskon kilpailu tiivistyy Lahden Paavolassa: uusi Citymarket avattiin tänään',N'https://yle.fi/a/74-20193108',N'Työllisyys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-25',N'Lah­ti pär­jää hy­vin kun­tien vä­li­ses­sä muut­to­liik­kees­sä',N'https://www.lahti.fi/uutiset/lahti-parjaa-hyvin-kuntien-valisessa-muuttoliikkeessa/',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-24',N'Woodio voitti Metsä360-tunnustuspalkinnon',N'https://www.kollinsaatio.fi/ajankohtaista/woodio-voitti-metsa360-tunnustuspalkinnon',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-24',N'Redoxin tarina alkoi olympiavuonna 1952 – nyt Hartolasta lähtee suksivoiteita lähes ympäri maailmaa',N'https://www.ess.fi/paikalliset/9018898',N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Aluekehitys, kulkuyhteydet ja kaavoitus','2025-11-21',N'Orimattilassa tehdään kotimaista muotia – näin se onnistuu kannattavasti, kestävästi ja vastuullisesti',N'https://www.ess.fi/paikalliset/9020986',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-21',N'Suomalainen Kirjakauppa avasi uuden myymälänsä kauppakeskus Triossa – tammikuussa tulossa myös uusi ruokakauppa',N'https://www.ess.fi/paikalliset/9017920',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL);
INSERT INTO catbxjbt_ennakointi.Mediaseuranta (Maakunta_ID,Teema,uutisen_pvm,Uutinen,Url,Hankkeen_luokitus,ai_analysis_status,ai_analyzed_at,ai_relevance_score,ai_economic_impact,ai_employment_impact,ai_key_sectors,ai_sentiment,ai_crisis_probability,ai_summary,ai_keywords,ai_full_analysis,ai_processing_time,competitive_analysis_status,competitive_analyzed_at,competitive_analysis,competitors_mentioned,funding_intelligence,market_opportunities,partnership_opportunities,competitive_score,business_relevance,strategic_importance,competitive_threats,market_intelligence,action_recommendations) VALUES
	 (1,N'Aluekehitys, kulkuyhteydet, kaavoitus ja asuinrakentaminen','2025-11-21',N'Vahva-?Jussin alueen nostokurki on harvinainen ilmiö näinä aikoina – puolet uudesta asuinalueesta kohta rakennettu',N'https://www.ess.fi/paikalliset/9017060',N'Aluekehitys, kulkuyhteydet ja kaavoitus',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Muutosneuvottelut, irtisanomiset, konkurssit, investointien perumiset ja tulosten heikentymiset','1900-01-01',N'Oilon irtisanoo muutosneuvotteluiden päätteeksi',N'https://www.ess.fi/paikalliset/9013904',N'Työllisyys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Aluekehitys, kulkuyhteydet ja kaavoitus','2025-11-19',N'Lahti tekee yritystonttikaupan Fazerin tulevan suklaatehtaan naapurissa',N'https://www.ess.fi/paikalliset/9013035',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Aluekehitys, kulkuyhteydet ja kaavoitus','2025-11-18',N'Lahden Nastolassa vireillä uusi myymälähanke valtatien liittymässä',N'https://www.ess.fi/paikalliset/9008125',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-26',N'Lah­den yri­tys­myön­tei­syys pa­ran­tu­nut edel­leen',N'https://www.lahti.fi/uutiset/lahden-yritysmyonteisyys-parantunut-edelleen/',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-18',N'Lah­ti kun­tien elin­voi­ma­ver­tai­lun vah­va nou­si­ja',N'https://www.lahti.fi/uutiset/lahti-kuntien-elinvoimavertailun-vahva-nousija/',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-11',N'Lahden Kujalan logistiikkakeskuksen seinässä lukee pian Alfarocin sijasta Warasto',N'https://www.ess.fi/paikalliset/8991485',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'','2025-11-03',N'Luhdan olym­pia­mallisto on tai­donnäyte sport­tisesta muodista vaih­televiin olo­suh­teisiin',N'https://lahtibusinessregion.fi/index.php?cID=868',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'','2025-11-18',N'Hol­lo­lalainen Ainoa Winery sai kas­vu­ra­hoituksen ja huip­puosaajia hal­li­tukseen',N'https://lahtibusinessregion.fi/uutisia/ainoa-winery-sai-kasvurahoituksen',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'','2025-11-11',N'Ministerivierailu Lahteen nosti esiin Päijät-Hämeen puolustusteollisuuden kasvupotentiaalin ',N'https://www.ladec.fi/tiedotteet/ministerivierailu-lahteen-nosti-esiin-paijat-hameen-puolustusteollisuuden-kasvupotentiaalin',N'Aluekehitys',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL);
INSERT INTO catbxjbt_ennakointi.Mediaseuranta (Maakunta_ID,Teema,uutisen_pvm,Uutinen,Url,Hankkeen_luokitus,ai_analysis_status,ai_analyzed_at,ai_relevance_score,ai_economic_impact,ai_employment_impact,ai_key_sectors,ai_sentiment,ai_crisis_probability,ai_summary,ai_keywords,ai_full_analysis,ai_processing_time,competitive_analysis_status,competitive_analyzed_at,competitive_analysis,competitors_mentioned,funding_intelligence,market_opportunities,partnership_opportunities,competitive_score,business_relevance,strategic_importance,competitive_threats,market_intelligence,action_recommendations) VALUES
	 (1,N'Aluekehitys, kulkuyhteydet, kaavoitus ja asuinrakentaminen','2025-11-24',N'Rakentaminen vilkastuu Hollolassa – tonttikauppa kasvussa',N'https://hollola.fi/ajankohtaista/uutiset/rakentaminen-vilkastuu-hollolassa-tonttikauppa-kasvussa/',N'Aluekehitys, kulkuyhteydet, kaavoitus ja asuinrakentaminen',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-26',N'Lahden yri­tys­myön­teisyys parantunut edelleen',N'https://lahtibusinessregion.fi/uutisia/lahden-yritysmyonteisyys-parantunut-edelleen?utm_source=newsletter&utm_medium=email&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-18',N'Lah­ti kun­tien elin­voi­ma­ver­tai­lun vah­va nou­si­ja',N'https://www.lahti.fi/uutiset/lahti-kuntien-elinvoimavertailun-vahva-nousija/',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-18',N'Hol­lo­lalainen Ainoa Winery sai kas­vu­ra­hoituksen ja huip­puosaajia hal­li­tukseen',N'https://lahtibusinessregion.fi/uutisia/ainoa-winery-sai-kasvurahoituksen?utm_source=newsletter&utm_medium=email&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-25',N'Vääksyyn raken­nettava maailman suurin hiekka-akku edistää kau­kolämmön hinnan tasaan­tumista ja alu­eellista elinvoimaa',N'https://lahtibusinessregion.fi/uutisia/vaaksyyn-rakennettava-maailman-suurin-hiekka-akku-edistaa-kaukolammon-hinnan-tasaantumista-ja-alueellista-elinvoimaa?utm_source=newsletter&utm_medium=email&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Investoinnit, kansainvälistyminen, toiminnan laajennus ja uudet työpaikat','2025-11-03',N'Luhdan olym­pia­mallisto on tai­donnäyte sport­tisesta muodista vaih­televiin olo­suh­teisiin',N'https://lahtibusinessregion.fi/index.php?cID=868?utm_source&utm_medium=email&utm_source=Lahti+vahvassa+nousussa%C2%A0%7C+V%C3%A4%C3%A4ksyyn+maailman+suurin+hiekka-akku%C2%A0%7C%C2%A0Luhta+pukee+Suomen+Olympiajoukkueen&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Koulutus ja tutkimus','2025-11-14',N'LUT-?yliopiston tavoitteet jälleen korkealla: järjestää Lahdessa "yliopistohistorian suurimman kasvutapahtuman"',N'https://www.ess.fi/paikalliset/8998656?utm_source=Lahti+vahvassa+nousussa%C2%A0%7C+V%C3%A4%C3%A4ksyyn+maailman+suurin+hiekka-akku%C2%A0%7C%C2%A0Luhta+pukee+Suomen+Olympiajoukkueen&utm_medium=email&utm_campaign=LBR_Uutiskirje_11%2F2025',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL),
	 (1,N'Elinvoima sekä veto- ja pitovoima','2025-11-26',N'Lahden yritysmyönteisyys parantunut edelleen - Ladecin suositteluhalukkuus suurten kaupunkien korkein',N'https://www.ladec.fi/tiedotteet/lahden-yritysmyonteisyys-parantunut-edelleen-ladecin-suositteluhalukkuus-suurten-kaupunkien-korkein',N'',N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'pending',NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'none',NULL,NULL,NULL,NULL);
